app/src/main/res/layout/fragment_review.xml
=> button size down

.idea/misc.xml
=> add picture

.idea/misc.xml, app/src/main/java/com/example/wmc/MainActivity.java, app/src/main/res/layout/fragment_cafe_registration.xml, app/src/main/res/layout/fragment_review.xml, app/src/main/res/layout/fragment_review_comment.xml, app/src/main/res/layout/fragment_search_default.xml
=> 카페 등록 페이지 작성

.idea/misc.xml, app/src/main/java/com/example/wmc/MainActivity.java, app/src/main/res/layout/fragment_cafe_modify.xml, app/src/main/res/layout/fragment_list.xml
=> 카페 수정 페이지 작성

.idea/deploymentTargetDropDown.xml, .idea/misc.xml, app/src/main/java/com/example/wmc/MainActivity.java, app/src/main/res/drawable/image_view_round.xml, app/src/main/res/layout/cafe_list_item.xml
=> drawable 이미지뷰 테두리 파일 추가

.idea/misc.xml, app/src/main/res/layout/fragment_list.xml
=> 카페 리스트 id 수정

app/src/main/res/layout/item_home_favoritelist.xml, app/src/main/res/layout/item_home_taglist.xml
=> Home_recyclerView item 생성

.idea/misc.xml, app/src/main/res/layout/fragment_cafe_delete.xml, app/src/main/res/layout/fragment_home.xml
=> cafe_delete 페이지 수정완료본 v1

.idea/misc.xml, app/src/main/java/com/example/wmc/MainActivity.java, app/src/main/res/layout/fragment_cafe_detail_more.xml
=> 카페 detail_more ( 리뷰 더보기 ) 레이아웃 수정 완

.idea/misc.xml, app/src/main/java/com/example/wmc/MainActivity.java, app/src/main/res/layout/fragment_mypage.xml
//푸터와 리뷰칸의 리사이클러뷰의 연동을 고민해봐야함.
=> mypage 페이지 레이아웃 수정 완료, 푸터 삽입 완료

.idea/misc.xml, app/src/main/java/com/example/wmc/MainActivity.java, app/src/main/res/layout/fragment_mypage_grade.xml
//푸터는 삽입하지않음. 하단 공간이 비었을때 대처법 고민?
=> mypage_grade 페이지 레이아웃 수정 완료

app/src/main/res/layout/fragment_mypage_grade.xml
//푸터는 삽입하지않음. 하단 공간이 비었을때 대처법 고민?
=> mypage_grade 페이지 레이아웃 수정 완료 v2

.idea/misc.xml, app/src/main/res/layout/fragment_review_tag.xml
=> review_tag 페이지 위 메뉴버튼 마진 변경

app/src/main/java/com/example/wmc/MainActivity.java, app/src/main/java/com/example/wmc/ReviewTagActivity.java
=> review_tag 페이지 위한 activity 파일 생성

app/src/main/java/com/example/wmc/ui/Fragment/ListFragment.java, app/src/main/res/layout/fragment_list.xml
=> ListFragment버튼 리스너 추가

app/src/main/java/com/example/wmc/ui/Fragment/ListCafelistFragment.java, app/src/main/res/layout/fragment_list_cafelist.xml, app/src/main/res/layout/fragment_list_search.xml
// ListCafelistFragment의 네비게이션이 아직 없음
=> ListCafelistFragment 검색창, 돋보기, 카페추가 플로팅 버튼 이벤트 추가

app/src/main/java/com/example/wmc/CafeDetail/CafeDetailAdapter.java, app/src/main/java/com/example/wmc/CafeDetail/CafeDetailFooterViewHolder.java, app/src/main/java/com/example/wmc/MainActivity.java, app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailMoreFragment.java, app/src/main/res/drawable/review_spinner.xml, app/src/main/res/layout/fragment_cafe_detail.xml, app/src/main/res/layout/fragment_cafe_detail_more.xml, app/src/main/res/layout/recyclerview_cafe_detail_footer.xml
CafeDetail에 예시 데이터 추가 및 리뷰더보기 클릭시 페이지 이동
=> CafeDetailMoreFragment의 스피너 클릭 이벤트추가

app/src/main/java/com/example/wmc/ui/Fragment/ReviewFragment.java, app/src/main/res/layout/fragment_review.xml
//작성완료 및 위치인증 아직 미구현
//검색창 클릭시 ListSearchFragment로 이동하는 네비게이션이 없음
=> ReviewFragment의 버튼 이벤트 추가

app/src/main/java/com/example/wmc/ui/Fragment/MyPageFragment.java, app/src/main/res/layout/fragment_mypage.xml
// 내가 쓴 리뷰 무한스크롤 관련 이슈발생, 푸터 포함 고민해야함
// 여행 가따와서 처리해야함
=> mypage 리사이클러뷰 (찜한 카페 완성, 내가 쓴 리뷰 미완성)

app/src/main/java/com/example/wmc/ui/Fragment/MyPageFragment.java, app/src/main/res/layout/fragment_mypage.xml
=> MyPage 리사이클러뷰 review 리사이클러뷰의 스크롤 죽임

app/src/main/res/layout/fragment_mypage.xml
// 리사이클러뷰 내부스크롤 다시살림, 아이템 안뜨는 문제
// 푸터 높이 20 늘려서 푸터 안짤리게 수정
=> MyPage 리사이클러뷰, 푸터 높이 설정

app/src/main/java/com/example/wmc/ui/Fragment/ListSearchFragment.java, app/src/main/res/layout/item_list_cafelist.xml
=> item_list_cafelist.xml 아이템 수정

app/src/main/res/layout/fragment_app_search_id_pw.xml, app/src/main/res/layout/fragment_app_signup.xml, app/src/main/res/layout/fragment_cafe_delete.xml, app/src/main/res/layout/fragment_cafe_detail.xml, app/src/main/res/layout/fragment_cafe_detail_more.xml, app/src/main/res/layout/fragment_cafe_modify.xml, app/src/main/res/layout/fragment_cafe_registration.xml, app/src/main/res/layout/fragment_mypage_grade.xml, app/src/main/res/layout/fragment_mypage_modify.xml, app/src/main/res/layout/fragment_review.xml, app/src/main/res/layout/fragment_review_comment.xml, app/src/main/res/layout/fragment_review_tag.xml
// 해당 페이지
app_search_id_pw
fragment_app_signup.xml
fragment_cafe_delete.xml
fragment_cafe_detail.xml
fragment_cafe_detail_more.xml
fragment_cafe_modify.xml
fragment_cafe_registration.xml
fragment_mypage_grade.xml
fragment_mypage_modify.xml
fragment_review.xml
fragment_review_comment.xml
fragment_review_tag.xml
=> 전체 페이지의 백스페이스 버튼 제거

app/src/main/res/layout/fragment_review_tag.xml
=> fragment_review_tag.xml 검색창 제거

app/src/main/java/com/example/wmc/ui/Fragment/ReviewTagFragment.java
// 삭제 버튼을 통해 항상 앞으로 채워넣기 활성화
// 태그를 데이터베이스로 반영할때 뒤의 블랭크 개수를 통해 반영할 수 있도록
=> ReviewTagFragment.java 태그 클릭 시 아래 3개의 버튼에 반영 활성화, 아래 3개 버튼의 삭제 버튼 활성화

app/src/main/java/com/example/wmc/ui/Fragment/ReviewTagFragment.java, app/src/main/res/layout/fragment_review_tag.xml, app/src/main/res/values/colors.xml
// colors.xml transper 색상 ( 투명 색상 ) 추가
// fragment_review_tag.xml 메뉴 초기값 또한 투명으로 설정
=> ReviewTagFragment.java 배경 색 선택되지 않은 메뉴는 투명으로 변경

app/src/main/res/layout/fragment_review.xml
// 레이팅바 (체크하는 원두) 위치 정렬, 이미지 크기 통합, 기기별 배치 의식
=> fragment_review.xml 맛,좌석,스터디 별점 레이아웃 배치 변경

app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailMoreFragment.java, app/src/main/res/layout/item_more_review.xml
// CafeDetailMoreFragment.java 페이지 3줄 이상의 리뷰 출력시 나오는 모습 확인
=> item_more_review.xml 리뷰 마진 수정, //

app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailMoreFragment.java, app/src/main/res/layout/fragment_cafe_detail_more.xml, app/src/main/res/layout/item_more_review.xml
=> fragment_cafe_detail_more.xml 푸터 투명화 (로고와 문구 삭제)

app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailFragment.java, app/src/main/res/layout/fragment_cafe_detail_more.xml
// CafeDetailFragment.java 그에 관한 코드 약간 수정. 스피너 실험을 위해 예시데이터 삽입을 시도했지만 실패.서버를 켜고 실험해봐야 할듯
=> fragment_cafe_detail_more.xml 스피너 스크롤뷰 밖으로 뺌

app/src/main/java/com/example/wmc/ui/Fragment/ListCafelistFragment.java, app/src/main/res/layout/item_more_review.xml
// notifyItemInserted
// item_more_review.xml 아이템 사진 마진 변경 (선안넘게)
=> ListCafelistFragment.java 리사이클러뷰 갱신 코드 작성 -->

app/src/main/java/com/example/wmc/ui/Fragment/CafeRegistrationFragment.java
//
openhour_substring, closehour_substring 변수 선언 후
운영시간에 대한 번들 정보만 2차 가공 후 표시하게 설정
=> CafeRegistrationFragment.java 운영시간 번들 수정 -->

app/src/main/java/com/example/wmc/ui/Fragment/MyPageFragment.java, app/src/main/res/layout/fragment_cafe_delete.xml, app/src/main/res/layout/fragment_cafe_detail.xml, app/src/main/res/layout/fragment_cafe_detail_more.xml, app/src/main/res/layout/fragment_cafe_modify.xml, app/src/main/res/layout/fragment_cafe_registration.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_list_cafelist.xml, app/src/main/res/layout/fragment_mypage.xml, app/src/main/res/layout/fragment_review.xml, app/src/main/res/layout/fragment_review_cafelist.xml, app/src/main/res/layout/fragment_review_comment.xml, app/src/main/res/layout/fragment_review_tag.xml
//
푸터 크기 조정 100dp -> 80dp
리뷰 더보기 페이지의 스피너 위로 집어넣기
리사이클러뷰 아이템 이중스크롤 막기 //NestedScrollview
=> 수정 사항 다수 -->

app/src/main/res/layout/item_more_review.xml, app/src/main/res/layout/recyclerview_cafe_detail_footer.xml
//
recyclerview_cafe_detail_footer.xml 마진 조절
=> item_more_review.xml 아이템 크기 조절 -->

app/src/main/res/layout/fragment_cafe_registration.xml
=> fragment_cafe_registration.xml 페이지 레이아웃 변경

app/src/main/java/com/example/wmc/MypageFavorite/MypageFavoriteAdapter.java, app/src/main/java/com/example/wmc/ui/Fragment/MyPageFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/ReviewCafeListFragment.java
등급, 이름, 찜한카페 리사이클러뷰, 중요도 1/2순위, 내가 쓴 리뷰 리사이클러뷰 연결 완료
personal, bookmark, cafe, review db 연결
=> MyPageFragment.java DB 연결 완료 , 리사이클러뷰 연결 -->

app/src/main/java/com/example/wmc/CafeDetail/CafeDetailAdapter.java, app/src/main/java/com/example/wmc/CafeDetail/CafeDetailItem.java, app/src/main/java/com/example/wmc/CafeDetailMore/CafeDetailMoreAdapter.java, app/src/main/java/com/example/wmc/CafeDetailMore/CafeDetailMoreItem.java, app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailMoreFragment.java
=> 카페 디테일과 리뷰더보기에서 프로필 이미지 설정

app/src/main/java/com/example/wmc/ui/Fragment/MyPageFragment.java, app/src/main/res/drawable/image_view_circle.xml, app/src/main/res/layout/fragment_mypage.xml
// 프로필 사진 설정 x의 경우, 기존 예시 이미지가 나오도록 함
=> 마이페이지 프로필 사진 보이도록 함

app/src/main/res/navigation/mobile_navigation.xml
카페디테일 -> 리뷰 + 코멘토리 작성 후,
뒤로가기 클릭 시, 작성했던 리뷰페이지 스택 삭제
=> 카페디테일 -> 리뷰

app/src/main/java/com/example/wmc/ui/Fragment/CafeRegistrationFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/FileUploadUtils.java, app/src/main/res/navigation/mobile_navigation.xml
// 카페 등록 시, 스택삭제하려면 지연시간이 필요해서 Dialog생성
=> 카페 등록 시, 카페 목록으로 돌아가기

.idea/gradle.xml, app/src/main/java/com/example/wmc/CafeDetail/CafeDetailAdapter.java, app/src/main/java/com/example/wmc/CafeDetail/CafeDetailItem.java, app/src/main/java/com/example/wmc/CafeDetailMore/CafeDetailMoreAdapter.java, app/src/main/java/com/example/wmc/CafeDetailMore/CafeDetailMoreItem.java, app/src/main/java/com/example/wmc/MypageReview/MypageReviewAdapter.java, app/src/main/java/com/example/wmc/MypageReview/MypageReviewItem.java, app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailMoreFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/MyPageFragment.java
리뷰 이미지 가져오기(카페디테일, 리뷰 더보기, 마이페이지)
=> 리뷰 이미지 가져오기(카페디테일, 리뷰 더보기, 마이페이지)

.idea/gradle.xml, app/src/main/java/com/example/wmc/FindidActivity.java, app/src/main/java/com/example/wmc/FindpwActivity.java, app/src/main/java/com/example/wmc/LoginAcivity.java, app/src/main/java/com/example/wmc/MainActivity.java, app/src/main/java/com/example/wmc/SignupActivity.java, app/src/main/res/layout/fragment_app_login.xml, app/src/main/res/layout/fragment_app_search_id.xml, app/src/main/res/layout/fragment_app_search_pw.xml, app/src/main/res/layout/fragment_app_signup.xml
=> 로그인/회원가입/idpw찾기 최종 // 문제1

app/src/main/java/com/example/wmc/LoginAcivity.java, app/src/main/java/com/example/wmc/SignupActivity.java, app/src/main/res/layout/fragment_app_login.xml
=> 로그인/회원가입/idpw찾기 최종2 // 문제1

app/src/main/java/com/example/wmc/ui/Fragment/Bottom_ReviewCafeListFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/CafeDetailMoreFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/HomeFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/ListCafelistFragment.java, app/src/main/java/com/example/wmc/ui/Fragment/MyPageFragment.java, app/src/main/res/values/strings.xml
=> 예시로 썼던 뚱이 사진 string으로 옮겨둠
